theme: jekyll-theme-minimal

title: Diep (Zoe) Tran
logo: "https://user-images.githubusercontent.com/59410249/104127268-741e2d80-5361-11eb-9040-6afcb87ce0ee.png"
description: >
  <a href="https://www.linkedin.com/in/diep-tran-ngoc/">LinkedIn</a> | <a href="https://github.com/dieptn1610">Github</a> | <a href="https://twitter.com/ZoeTran01">Twitter</a>
  <br><br>
  I am pursuing a Bachelor of Business Administration at University of Tartu, Estonia.
  <br><br>
  Aspiring data analyst with years of international experience, team motivation and charismatic communication skills.
