theme: jekyll-theme-minimal

title: Diep (Zoe) Tran
logo: "https://user-images.githubusercontent.com/59410249/103689173-3c933800-4f93-11eb-980e-3fdf64118695.png"
description: >
  <a href="https://www.linkedin.com/in/diep-tran-ngoc/">LinkedIn</a> | <a href="https://github.com/dieptn1610">Github</a>
  <br><br>
  I am pursuing a Bachelor of Business Administration at University of Tartu, Estonia.
  <br>
  Aspiring data analyst with years of international experience, team motivation and charismatic communication skills.
