theme: jekyll-theme-minimal

title: Diep (Zoe) Tran
logo: "https://user-images.githubusercontent.com/59410249/103591034-48c5b980-4eef-11eb-85ff-62ed9e797ebc.jpg"
description: >
  <a href="https://www.linkedin.com/in/diep-tran-ngoc/">LinkedIn</a> | <a href="https://github.com/dieptn1610">Github</a>
  <br><br>
  I am pursuing a Bachelor of Business Administration at University of Tartu, Estonia.
  <br>
  Aspiring data analyst with years of international experience, team motivation and charismatic communication skills.
  
  
<style type="text/css">

h1.title {
  font-size: 38px;
  color: DarkRed;
  text-align: center;
}

h4.description { /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
  text-align: center;
}
</style>
