theme: jekyll-theme-minimal

title: Diep (Zoe) Tran
logo: 
description: >
  Business student @ UniTartu
  Aspiring data analyst
  <br><br> 
  <a href="https://www.linkedin.com/in/diep-tran-ngoc/">View my LinkedIn profile</a>
  
